### PR TITLE
execute local git config user.name & user.email for /etc/.git

### PR DESCRIPTION
**Pull request by monotek**
fixes https://github.com/bodgit/puppet-etckeeper/issues/3

### CODE REVIEW

**Comment by monotek** [comment]
Don't merge please. The problem only occurs on centos if you login via root directly. 
Problem hast to be fixed in etckeeper.

**Comment by monotek** [comment]
Still needed for Debian/Ubuntu when unattended-upgrades are used. See https://github.com/bodgit/puppet-etckeeper/issues/3

**Comment by bodgit** [comment]
Does configuring the name and email mean that if you become root via `su` or `sudo` that it no longer picks up the original user and always uses the configured details in the commit messages? I will have to see if setting `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` overrides the settings as that's what etckeeper does in that scenario.

For setting  them, I would probably prefer to use something like `puppet/inifile` to manage the settings rather than rely on `exec` so Puppet will continually enforce them.

**Comment by bodgit** [comment]
I've uploaded v1.2.0 to the forge which hopefully fixes #3, #4 and #7. Thanks for the bug report(s)!

**Pull request closed without merging**
